document.write("<table border='1'>");
document.write("<tr>");
document.write("<td>navigator.appName: </td>");
document.write("<td>"+navigator.appName+"</td>");
document.write("</tr>");
document.write("<tr>");
document.write("<td>navigator.appVersion: </td>");
document.write("<td>"+navigator.appVersion+"</td>");
document.write("</tr>");
document.write("<tr>");
document.write("<td>navigator.appCodeName: </td>");
document.write("<td>"+navigator.appCodeName+"</td>");
document.write("</tr>");
document.write("<tr>");
document.write("<td>navigator.cookieEnabled: </td>");
document.write("<td>"+navigator.cookieEnabled+"</td>");
document.write("</tr>");
document.write("<tr>");
document.write("<td>navigator.userAgent: </td>");
document.write("<td>"+navigator.userAgent+"</td>");
document.write("</tr>");
document.write("<tr>");
document.write("<td>navigator.language: </td>");
document.write("<td>"+navigator.language+"</td>");
document.write("</tr>");
document.write("<tr>");
document.write("<td>navigator.userLanguage: </td>");
document.write("<td>"+navigator.userLanguage+"</td>");
document.write("</tr>");
document.write("<tr>");
document.write("<td>navigator.plugins: </td>");
document.write("<td>"+navigator.plugins+"</td>");
document.write("</tr>");
document.write("<tr>");
document.write("<td>navigator.systemLanguage: </td>");
document.write("<td>"+navigator.systemLanguage+"</td>");
document.write("</tr>");
document.write("<tr>");
document.write("<td>navigator.mimeTypes: </td>");
document.write("<td>"+navigator.mimeTypes+"</td>");
document.write("</tr>");
document.write("<tr>");
document.write("<td>navigator.platform: </td>");
document.write("<td>"+navigator.platform+"</td>");
document.write("</tr>");
document.write("<tr>");
document.write("<td>navigator.online: </td>");
document.write("<td>"+navigator.online+"</td>");
document.write("</tr>");
document.write("/<table>");